version: "3"

services:
  app:
    container_name: golang-app
    build:
      context: .
      dockerfile: Dockerfile.limited
      tags:
        - fullcycle
        - learning
    image: vytorbrb/fullcycle
